### ISSUE TITLE
MQTT not sending any requests

### ISSUE THREAD

**Issue by mukowman** [meatpiHQ/wican-fw#10]
Recently received the WiCAN module. I was able to get the battery alert setup and publishing to MQTT successfully, but can't seem to get the MQTT module to work by itself. Using the same MQTT settings I cannot see anything published to the MQTT server. Not sure on the best way to check the logs on this device. Any help would be appreciated.

**Comment by mukowman** [comment]
Reviewing the code I did notice in the mqtt.c file seems to have some hard coded values in the unit as opposed to the sleep mode pulls them from the config

`void mqtt_init(char* id, uint8_t connected_led, QueueHandle_t *xtx_queue)
{
    esp_mqtt_client_config_t mqtt_cfg = {
        .uri = "mqtt://192.168.31.2",
		.port = 1883,
		.username = "meatpi",
		.password = "meatpi",
		.disable_auto_reconnect = false,
		.reconnect_timeout_ms = 5000,
		.out_buffer_size = 1024*5,
        .buffer_size = 1024*5,
		.lwt_topic = mqtt_status_topic,
		.lwt_msg = "{\"status\": \"offline\"}",
		.keepalive`

**Comment by meatpiHQ** [comment]
@mukowman yup looks like that's the problem. I'll release a new version with the fix.

**Comment by meatpiHQ** [comment]
@mukowman please try this firmware and let me know.

[wican-fw_v164_hv300.zip](https://github.com/meatpiHQ/wican-fw/files/10569438/wican-fw_v164_hv300.zip)

**Comment by mukowman** [comment]
Working perfect now. Thank you for the quick response

**Comment by spali** [comment]
Had the same problem, can also confirm the above firmware works and status is now published as expected.

**Comment by zebraelch** [comment]
I just downloaded and installed fw 1.64 ..but i forgot i have the wican_usb .. now, not sure this fw is compatible? I do see the wican topic in mqqt-explorer though :)

**Comment by meatpiHQ** [comment]
@zebraelch firmware is not fully compatible, v1.64 is already released for USB and OBD

https://github.com/meatpiHQ/wican-fw/releases/tag/v1.64

**Comment by zebraelch** [comment]
thank you, all good now :) time to get the home assistant part going.

**Comment by karlmikko** [comment]
I had the same issue - then installed the firmware above - now I get mqtt messages to my broker but carscanner can no longer connect.
