### ISSUE TITLE
How to get SoC for Opel Mokka-e in HA

### ISSUE THREAD

**Issue by jove01** [meatpiHQ/wican-fw#116]
Hello
I have a Opel Mokka-e. With the PSA-addon in HA and EVCC all works fine. But now, it seems, that Opel cut all external way to get info from the car. So I am looking for an alternativ and found meatpi and the project here.
After step by step an the helpfully site with the example, I get my first MQTT-Message in the explorer. But it is not the SoC, it is the payload of the automation.
In CarScanner see the SoC (and other) but I did not know how to tranform the information from CarScanner to this PID.
![share_3924102209795471429](https://github.com/meatpiHQ/wican-fw/assets/116289742/89ea32b7-e222-4776-9b05-336339e21ec7)
Can someone help?
Thanks

**Comment by chris58008** [comment]
Did you look at this guide? https://github.com/meatpiHQ/wican-fw/wiki/EV-Battery-SoC-in-Home-Assistant-%E2%80%90-Example

**Comment by jove01** [comment]
Yes, that is my guideline. But the result in the mqtt-explorer ist not the Soc, I see

{"bus":"0","type":"rx","ts":21782,"frame":[{"id":1995,"dlc":8,"rtr":false,"extd":false,"data":[5,98,3,8,2,69,204,204]}]}

 

Tomorrow I can show it as a copy from the explorer.

Thanks

 

Von: chris58008 ***@***.***> 
Gesendet: Samstag, 6. April 2024 23:26
An: meatpiHQ/wican-fw ***@***.***>
Cc: jove01 ***@***.***>; Author ***@***.***>
Betreff: Re: [meatpiHQ/wican-fw] How to get SoC for Opel Mokka-e in HA (Issue #116)

 

Did you look at this guide? https://github.com/meatpiHQ/wican-fw/wiki/EV-Battery-SoC-in-Home-Assistant-%E2%80%90-Example

**Comment by jove01** [comment]
Today I get no connection to the ECU (yesterday no problem)
I found this [https://github.com/meatpiHQ/wican-fw/issues/17#issuecomment-1456925171](url) with the settings for CarScanner. It did not help.
Tomorrow I will look deeper in this thread, or do you have a tip.

**Comment by meatpiHQ** [comment]
@jove01 please post a screenshot of the device configuration page.

**Comment by jove01** [comment]
> @jove01 please post a screenshot of the device configuration page.

I will do it in the evening

**Comment by jove01** [comment]
First the settings in WiCan

![grafik](https://github.com/meatpiHQ/wican-fw/assets/116289742/7524689c-89b5-4fa8-82c1-f5cb5e81e352)
![grafik](https://github.com/meatpiHQ/wican-fw/assets/116289742/f11e6111-3d2a-487e-bfed-88b70c7ce2ff)


![Screenshot 2024-04-07 175016](https://github.com/meatpiHQ/wican-fw/assets/116289742/9aa05769-193d-46c4-8917-c8ae59d12db7)
![Screenshot 2024-04-07 181035](https://github.com/meatpiHQ/wican-fw/assets/116289742/8b268ca9-88b3-4b58-ab50-f3a1f10fff43)
![Screenshot 2024-04-07 181203](https://github.com/meatpiHQ/wican-fw/assets/116289742/b8aeb45b-0e3a-4bb4-858e-4f71f32893d5)

Than HA Automation
`service: mqtt.publish
data:
  qos: 0
  retain: false
  topic: wican/5432049xxxxx/can/tx
  payload: >-
    {"bus":"0","type":"tx","ts":21767,"frame":[{"id":1931,"dlc":8,"rtr":false,"extd":false,"data":[3,34,3,8,170,170,170,170]}]}
`
The Result
`{"bus":"0","type":"tx","ts":21767,"frame":[{"id":1931,"dlc":8,"rtr":false,"extd":false,"data":[3,34,3,8,170,170,170,170]}]}`

Car Scanner
![share_392284176567646](https://github.com/meatpiHQ/wican-fw/assets/116289742/c18849e0-cdd7-4ff8-b91b-5ba2a76a8ed0)


I reinstalled Car Scanner, but **no connection to ECU**!

Than I tried it with iCar Pro and SkyScanner, no Problem

Maybe the ECU-Problem ist the basic-problem. And I did not know, what ist happend to yesterday, I had the connection and I see  the SoC!

**Comment by jove01** [comment]
So tried the HA AddOn PSA Car controller again. And after many tries the add On works. So I will  stop the WiCan implementation. Maybe later I try it again, I think it is a good project.
Godd luck and many thnanks.
