### ISSUE TITLE
BLE won't Enable

### ISSUE THREAD

**Issue by edlucky1** [meatpiHQ/wican-fw#120]
Unable to enable BLE. When enable is selected the drop down box turns gray and shows disabled. Unable to select options again until after rebooting device. Firmware 2.98

![image](https://github.com/meatpiHQ/wican-fw/assets/76714493/676d5021-b9c3-4ef5-885f-279c56ded732)

**Comment by meatpiHQ** [comment]
@edlucky1 set the wifi mode to AP.

**Comment by edlucky1** [comment]
That worked, but I wanted to use BLE to run Car Scanner will logging to MQTT. Is AP mode a requirement for BLE?

**Comment by meatpiHQ** [comment]
> Is AP mode a requirement for BLE?

Yes. 

You can use car scanner on wifi to log mqtt.

**Comment by edlucky1** [comment]
Got it... user error with Car Scanner. Thanks!
