### ISSUE TITLE
Please help with BMW CAN bus mileage

### ISSUE THREAD

**Issue by alexdan-77** [meatpiHQ/wican-fw#123]
Hello everyone!

Trying to ask by CAN bus this request (odometer mileage):
{"bus":"0","type":"tx","frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,166,170,170,170,170,170]}]}

but no reply at all. nor BMW neither SKODA. seems they dont support this request.

but when ask with this request (get fuel level):
{"bus":"0","type":"tx","frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,47,170,170,170,170,170]}]}
i have reply with correct result.

are there any correct PIDs to achieve my goal?

thanks.

**Comment by meatpiHQ** [comment]
@alexdan-77 it's possible that your car doesn't support this PID. 

Have you tried Carscanner app? Are you able to see the Odometer value in the app?

**Comment by alexdan-77** [comment]
> @alexdan-77 it's possible that your car doesn't support this PID.
> 
> Have you tried Carscanner app? Are you able to see the Odometer value in the app?

nope.
![Screenshot_20240503_152814](https://github.com/meatpiHQ/wican-fw/assets/75975043/a0e8857d-89e0-439d-be59-5278a6d53b92)

**Comment by alexdan-77** [comment]
maybe somebody knows request that works?or is it impossible by can bus?

**Comment by meatpiHQ** [comment]
@alexdan-77 Try other apps other than carscanner. I also suggest you try and look at some BMW forum, it's possible that someone has already figured it out.

**Comment by alexdan-77** [comment]
tell me. if i use canhacker app will it show something useful?

**Comment by alexdan-77** [comment]
i use savvycan scanner. of course my engine is on.

**Comment by meatpiHQ** [comment]
@alexdan-77 some cars don't expose the internal CAN bus on the OBD connector. The 0x7E8 is the OBD response, but I don't know what is 0x130.
