### ISSUE TITLE
Odometer PID 166 Value

### ISSUE THREAD

**Issue by edlucky1** [meatpiHQ/wican-fw#124]
I am able to get this response:

```{"bus":"0","type":"rx","ts":24909,"frame":[{"id":2024,"dlc":8,"rtr":false,"extd":false,"data":[6,65,166,0,20,187,199,170]}]}```

Wican settings:

![image](https://github.com/meatpiHQ/wican-fw/assets/76714493/cd5a581e-8039-4a31-bfda-3486e5216ef4)

This results in a value of 173925333. My car odometer (in miles converted to km, km is standard unit for this PID) is 135,086.

![image](https://github.com/meatpiHQ/wican-fw/assets/76714493/a8b12fdf-efa4-4301-977e-09c00ddab96b)

**Comment by edlucky1** [comment]
After some testing start bit should be 24 in order to get correct value. Wican settings:

![image](https://github.com/meatpiHQ/wican-fw/assets/76714493/98d86504-bc9e-4607-9319-808121710e14)

I included the conversion from km to miles. For some reason my car (Hyundai Sonata) appears to have an offset of 2 miles. I will monitor this to make sure the offset doesn't change over time.

**Comment by meatpiHQ** [comment]
@edlucky1 looks good!
