### ISSUE TITLE
Problem retrieving information from mqtt

### ISSUE THREAD

**Issue by ToniRos** [meatpiHQ/wican-fw#126]
I have problems recovering the information with MQTT, I have activated the elm327 log, I have recovered the frames (I can only do this by connecting in AP mode, as a client of the IP assigned in Station it is not possible, doen not connect)
The log is:
```
09/05/2024 19:15:40(-0.37 seconds) 
{"bus":"0","type":"rx","ts":3111,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[38,0,0,0,0,0,0,0]}]}
09/05/2024 19:15:40(-0.05 seconds) 
{"bus":"0","type":"rx","ts":3096,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[37,0,0,0,0,0,0,0]}]}
09/05/2024 19:15:40(-0 seconds) 
```
{"bus":"0","type":"rx","ts":3081,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[36,0,1,1,0,40,13,**192**]}]}
```
09/05/2024 19:15:40(-0 seconds) 
{"bus":"0","type":"rx","ts":3066,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[35,35,40,1,0,100,206,206]}]}
09/05/2024 19:15:40(-0.05 seconds) 
{"bus":"0","type":"rx","ts":3051,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[34,23,0,0,0,0,29,238]}]}
09/05/2024 19:15:40(-0 seconds) 
{"bus":"0","type":"rx","ts":3036,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[33,0,0,0,0,0,23,23]}]}
09/05/2024 19:15:40(-0 seconds) 
```
**{"bus":"0","type":"tx","ts":3024,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[48,0,10,170,170,170,170,170]}]}**
```
09/05/2024 19:15:40(-0 seconds) 
{"bus":"0","type":"rx","ts":3021,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[16,44,97,5,255,255,255,255]}]}
09/05/2024 19:15:40(-0.05 seconds) 
```
**{"bus":"0","type":"tx","ts":3013,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[2,33,5,170,170,170,170,170]}]}**
```
09/05/2024 19:15:39(-0.61 seconds) 
```
**{"bus":"0","type":"tx","ts":2402,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}**
```
09/05/2024 19:15:39(-0.51 seconds) 
{"bus":"0","type":"tx","ts":1892,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
09/05/2024 19:15:38(-0.47 seconds) 
{"bus":"0","type":"tx","ts":1427,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
09/05/2024 19:15:38(-0.46 seconds) 
{"bus":"0","type":"tx","ts":970,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
09/05/2024 19:15:37(-0.61 seconds) 
{"bus":"0","type":"tx","ts":359,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
09/05/2024 19:15:37(-0.47 seconds) 
{"bus":"0","type":"tx","ts":59892,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
09/05/2024 19:15:36(-0.41 seconds) 
{"bus":"0","type":"tx","ts":59484,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
09/05/2024 19:15:36(-0.45 seconds) 
{"bus":"0","type":"tx","ts":59031,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
09/05/2024 19:15:35(-0.42 seconds) 
{"bus":"0","type":"tx","ts":58606,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
09/05/2024 19:15:35(-0.46 seconds) 
{"bus":"0","type":"tx","ts":58120,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
09/05/2024 19:15:35(-0.44 seconds) 
{"bus":"0","type":"tx","ts":57711,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
09/05/2024 19:15:34(-0.43 seconds) 
{"bus":"0","type":"tx","ts":57284,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
09/05/2024 19:15:34(-0.42 seconds) 
{"bus":"0","type":"tx","ts":56862,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
09/05/2024 19:15:33(-0.48 seconds) 
{"bus":"0","type":"tx","ts":56379,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
09/05/2024 19:15:33(-0.35 seconds) 
{"bus":"0","type":"rx","ts":55973,"frame":[{"id":2026,"dlc":8,"rtr":false,"extd":false,"data":[6,65,32,0,1,128,0,0]}]}
09/05/2024 19:15:33(-0.05 seconds) 
{"bus":"0","type":"rx","ts":55971,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[6,65,32,0,1,128,0,0]}]}
09/05/2024 19:15:33(-0 seconds) 
{"bus":"0","type":"tx","ts":55964,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,32,170,170,170,170,170]}]}
09/05/2024 19:15:32(-0.37 seconds) 
{"bus":"0","type":"rx","ts":55559,"frame":[{"id":2026,"dlc":8,"rtr":false,"extd":false,"data":[6,65,0,128,0,0,1,0]}]}
09/05/2024 19:15:32(-0 seconds) 
{"bus":"0","type":"rx","ts":55556,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[6,65,0,128,0,0,1,0]}]}
09/05/2024 19:15:32(-0.05 seconds) 
{"bus":"0","type":"tx","ts":55550,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,0,170,170,170,170,170]}]}
09/05/2024 19:15:32(-0.5 seconds) 
{"bus":"0","type":"rx","ts":55016,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[6,65,0,128,0,0,1,0]}]}
09/05/2024 19:15:32(-0 seconds) 
{"bus":"0","type":"rx","ts":55013,"frame":[{"id":2026,"dlc":8,"rtr":false,"extd":false,"data":[6,65,0,128,0,0,1,0]}]}
09/05/2024 19:15:32(-0.04 seconds) 
{"bus":"0","type":"tx","ts":55006,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,0,170,170,170,170,170]}]}
09/05/2024 19:15:31(-0.39 seconds) 
{"bus":"0","type":"rx","ts":54577,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[6,65,0,128,0,0,1,0]}]}
09/05/2024 19:15:31(-0.05 seconds) 
{"bus":"0","type":"tx","ts":54567,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,0,170,170,170,170,170]}]}
09/05/2024 19:15:31(-0.37 seconds) 
{"bus":"0","type":"rx","ts":54151,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[6,65,0,128,0,0,1,0]}]}
09/05/2024 19:15:31(-0 seconds) 
{"bus":"0","type":"rx","ts":54149,"frame":[{"id":2026,"dlc":8,"rtr":false,"extd":false,"data":[6,65,0,128,0,0,1,0]}]}
09/05/2024 19:15:31(-0.05 seconds) 
{"bus":"0","type":"tx","ts":54141,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,0,170,170,170,170,170]}]}
09/05/2024 19:15:31(-0.43 seconds) 
{"bus":"0","type":"rx","ts":53573,"frame":[{"id":2026,"dlc":8,"rtr":false,"extd":false,"data":[6,65,0,128,0,0,1,0]}]}
09/05/2024 19:15:31(-0.05 seconds) 
{"bus":"0","type":"rx","ts":53571,"frame":[{"id":2028,"dlc":8,"rtr":false,"extd":false,"data":[6,65,0,128,0,0,1,0]}]}
09/05/2024 19:15:30(-0.1 seconds) 
{"bus":"0","type":"tx","ts":53565,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,0,170,170,170,170,170]}]}
```

I mark the plots that I think are relevant to the indicator I want:

When I send these frames via MQTT I do not receive the expected response frames, but as soon as I connect Car Scanner (connecting to the AP) everything works perfectly, and I start receiving data. Although it does not explicitly ask for the indicator I want.

The version I have is:
Firmware ver: | v2.98
Hardware ver: | v3.00_obd

**Comment by meatpiHQ** [comment]
@ToniRos can you please post your device configuration page.

Did you turn off the "elm327 log" before sending the tx frame?

**Comment by ToniRos** [comment]
@meatpiHQ yes I turn off the eml327 log.

![image](https://github.com/meatpiHQ/wican-fw/assets/33701571/67457aeb-6898-47cd-85c7-66c5559e5265)

Thanks

**Comment by ToniRos** [comment]
Thanks @meatpiHQ .

After a few tests, mysteriously I can now connect Car Scanner in station mode. I have created this automation in HomeAssistant:
`
action:
  - alias: Send Tx CANID:2015 PID:0
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":18197,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,0,170,170,170,170,170]}]}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 700
  - alias: Send Tx CANID:2015 PID:32
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":19661,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,32,170,170,170,170,170]}]}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 1100
  - alias: Send Tx CANID:2015 PID:0
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":20822,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,0,170,170,170,170,170]}]}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 700
  - alias: Send Tx CANID:2015 PID:2
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":21505,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,9,2,170,170,170,170,170]}]}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 10
  - alias: Send Tx CANID:2015 PID:10 Receive multiframe
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":21520,"frame":[{"id":2018,"dlc":8,"rtr":false,"extd":false,"data":[48,0,10,170,170,170,170,170]}]}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 700
  - alias: Send Tx CANID:2015 PID:4
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":22209,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,9,4,170,170,170,170,170]}]}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 10
  - alias: Send Tx CANID:2015 PID:10 Receive multiframe
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":22219,"frame":[{"id":2018,"dlc":8,"rtr":false,"extd":false,"data":[48,0,10,170,170,170,170,170]}]}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 10
  - alias: Send Tx CANID:2015 PID:10 Receive multiframe
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":22222,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[48,0,10,170,170,170,170,170]}]}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 700
  - alias: Send Tx CANID:2015 PID:10
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":22922,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,9,10,170,170,170,170,170]}]}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 10
  - alias: Send Tx CANID:2015 PID:10 Receive multiframe
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":22935,"frame":[{"id":2018,"dlc":8,"rtr":false,"extd":false,"data":[48,0,10,170,170,170,170,170]}]}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 10
  - alias: Send Tx CANID:2015 PID:10 Receive multiframe
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":22937,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[48,0,10,170,170,170,170,170]}]}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - alias: Send Tx CANID:2015 PID:17 (Rx BattPackRemain CANID:2028 PID:17)
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":58606,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - alias: Send Tx CANID:2015 PID:17 (Rx BattPackRemain CANID:2028 PID:17)
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":2402,"frame":[{"id":2015,"dlc":8,"rtr":false,"extd":false,"data":[2,1,17,170,170,170,170,170]}]}
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - alias: Send Tx - CANID:2020 PID:5 (To Trigger 2101)
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":56245,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[2,33,5,170,170,170,170,170]}]}
    enabled: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 20
  - alias: >-
      (After Receiving the ack Rx....) Send Tx - CANID:2020 PID:10 (To Trigger
      "real" 2101)
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":56254,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[48,0,10,170,170,170,170,170]}]}
    enabled: true
mode: single
`
It runs every minute, and the result reveived is:

`
11/05/2024 3:02:08 
{"BattDisplay": 79.500000}
11/05/2024 2:50:08(-12 minutes) 
{"BattDisplay": 77.500000}
11/05/2024 2:38:08(-12 minutes) 
{"BattDisplay": 76.000000}
11/05/2024 2:36:08(-2 minutes) 
{"BattDisplay": 75.500000}
11/05/2024 2:33:08(-3 minutes) 
{"BattDisplay": 75.000000}
11/05/2024 2:28:08(-5 minutes) 
{"BattDisplay": 74.500000}
11/05/2024 2:25:08(-3.01 minutes) 
{"BattDisplay": 74.000000}
11/05/2024 2:24:08(-59.98 seconds) 
{"BattDisplay": 74.000000}
11/05/2024 2:16:08(-8 minutes) 
{"BattDisplay": 72.500000}
11/05/2024 2:10:08(-6 minutes) 
{"BattDisplay": 72.000000}
11/05/2024 2:04:08(-6 minutes) 
{"BattDisplay": 71.000000}
11/05/2024 1:57:08(-7 minutes) 
{"BattDisplay": 70.000000}
11/05/2024 1:52:08(-5 minutes) 
{"BattDisplay": 69.500000}
11/05/2024 1:48:08(-4 minutes) 
{"BattDisplay": 69.000000}
11/05/2024 1:34:08(-14 minutes) 
{"BattDisplay": 67.500000}
11/05/2024 1:32:08(-2 minutes) 
{"BattDisplay": 67.500000}
`
Battery charging starts at 1:30 and ends when it reaches 80%.

Any idea why the response is not received every minute?

**Comment by ToniRos** [comment]
@meatpiHQ 

I finally found the trick!
Everything ok with the WiCan configuration.
I simply simplified sending from homeassistant and I do it every second, with this I indicate that I receive the status constantly.

```
alias: Check Kia Battery Charge Display
description: ""
trigger:
  - platform: time_pattern
    seconds: /1
condition:
  - condition: state
    entity_id: sensor.wican_status
    state: online
action:
  - alias: Send Tx - CANID:2020 PID:5 (To Trigger 2101)
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":56245,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[2,33,5,170,170,170,170,170]}]}
    enabled: true
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 20
  - alias: >-
      (After Receiving the ack Rx....) Send Tx - CANID:2020 PID:10 (To Trigger
      "real" 2101)
    service: mqtt.publish
    metadata: {}
    data:
      qos: "0"
      topic: wican/xxxx/can/tx
      payload: >-
        {"bus":"0","type":"tx","ts":56254,"frame":[{"id":2020,"dlc":8,"rtr":false,"extd":false,"data":[48,0,10,170,170,170,170,170]}]}
    enabled: true
mode: single
```

Thank you very much, and I'm sorry for the inconvenience.

**Comment by ToniRos** [comment]
I close the issue. Thanks again.

**Comment by meatpiHQ** [comment]
@ToniRos glad to hear you got it working. Btw what is your car make and model? in case someone else might find this info useful.

**Comment by ToniRos** [comment]
Kia Soul EV 2015
