### ISSUE TITLE
100 identical RX Messages per second

### ISSUE THREAD

**Issue by zugif** [meatpiHQ/wican-fw#127]
Hi,

sorry for the question, maybe i'm misunderstanding something.
Yesterday i was able to get the SoC and Temperature of my car via MQTT via the NodeRed Example.
Since today saw that i get 100 RX-Messages per second which all look like this:

{"bus":"0","type":"rx","ts":**46851**,"frame":[{"id":2029,"dlc":8,"rtr":false,"extd":false,"data":[**33**,170,170,170,170,170,170,170]}]}

Only the bold parts change, they seem to increase very fast:

![grafik](https://github.com/meatpiHQ/wican-fw/assets/9107833/1d7c7b1b-4153-43d2-be7e-856df5e7f4e2)

Now when i'm sending a new TX request i dont seem to get the answer. 
I tried using the filter, but it seems like the correct answer is not beeing send from the car, so i dont get any messages after that.

Is there maybe a setting i need to update? Or does that specific RX message mean something special?

Im using:
Firmware ver: v2.98
Hardware ver: v3.00_obd

</body>
</html>

Thanks and BR

**Comment by meatpiHQ** [comment]
@zugif Do you still see this Rx message when if you stop NodeRED?

Please post your tx and rx frames I can help you setup the filters.
