### ISSUE TITLE
Special Character "%" in WIFI Password do not work

### ISSUE THREAD

**Issue by marten-lucas** [meatpiHQ/wican-fw#14]
My Wifi-Password contains the Percent Sign "%". the WiCan does not connect.

**Comment by meatpiHQ** [comment]
@marten-lucas password with % is not stored for some reason. I'll fix this in the next release.

**Comment by meatpiHQ** [comment]
@marten-lucas fixed please update to the version v1.65, there's a major bug fix

https://github.com/meatpiHQ/wican-fw/releases/tag/v1.65

**Comment by marten-lucas** [comment]
works! Thank you!
