### ISSUE TITLE
reboot via webinterface

### ISSUE THREAD

**Issue by marten-lucas** [meatpiHQ/wican-fw#15]
There is a prompt that reads "reboot after monitoring". Would be great if this is possible from the web interface.

**Comment by meatpiHQ** [comment]
@marten-lucas will be added in the next release.

**Comment by meatpiHQ** [comment]
@marten-lucas new reboot button in the about tab. [v1.65](https://github.com/meatpiHQ/wican-fw/releases/tag/v1.65)

**Comment by marten-lucas** [comment]
works! Thank you!
