### ISSUE TITLE
Reading SOC of BYD Seal

### ISSUE THREAD

**Issue by gerdluthe** [meatpiHQ/wican-fw#151]
Anybody know the PIDs for the BYD Seal to read out the SOC or any other data
Nothing found till yet :-(

**Comment by meatpiHQ** [comment]
@gerdluthe Here you go https://github.com/meatpiHQ/wican-fw/discussions/122

**Comment by gerdluthe** [comment]
Thanks for this very fast reply.
Checked it out and it works for me 

Great support
