### ISSUE TITLE
WiCAN attached =  cant control climate on Hyundai Ioniq5

### ISSUE THREAD

**Issue by tung256** [meatpiHQ/wican-fw#165]
when unit is attached to my Hyundai Ioniq 5 (2023 SEL AWD), i cannot control the car's climate at all.  the touchscreen on dashboard are greyed out. the physical black bar below the touchscreen is also blanked out. no way to turn the fans nor temp on.  
![image](https://github.com/user-attachments/assets/43e16e3c-094a-4161-8273-02ae192e312b)

any idea why?
once i remove the WiCAN, i can control everything again.

here are my settings for the WiCAN module:
![image](https://github.com/user-attachments/assets/3e377515-ac2e-439b-b3c7-77462d662204)

**Comment by meatpiHQ** [comment]
@tung256 are you sending anything on MQTT to the CAN bus?

Try disabling mqtt and changing CAN mode to silent instead of normal. You cannot really use the adapter in silent mode, but this will tell us that the issue is caused by CAN. 

It's possible that the CAN bitrate is not 500k, I know other users are using it with Ioniq. Don't leave the adapter plugged in for long until we figure it out.

**Comment by tung256** [comment]
ok. so i enable MQTT to get the CAN ID. once i get CAN ID, i should disable MQTT?
as of now, everything is enabled and i am still able to control Climate.  i guess once i disconnect the WiCAN, and reconnect (without making any changes on the WiCAN settings), the car works as normal.


    On Sunday, July 28, 2024 at 12:58:49 PM EDT, MeatPi Electronics ***@***.***> wrote:  
 
 


@tung256 are you sending anything on MQTT to the CAN bus?

Try disabling mqtt and changing CAN mode to silent instead of normal. You cannot really use the adapter in silent mode, but this will tell us that the issue is caused by CAN.

It's possible that the CAN bitrate is not 500k, I know other users are using it with Ioniq. Don't leave the adapter plugged in for long until we figure it out.

**Comment by meatpiHQ** [comment]
@tung256 what if you set CAN mode to "Normal" does the  climate control stops working? Keep the mqtt disabled and test with carscanner see if you can see values other than the 12V battery voltage. The 12V battery reading is not done through CAN.

First we need to figure out what is causing the  climate control to act up before we set it up.

**Comment by tung256** [comment]
> @tung256 what if you set CAN mode to "Normal" does the climate control stops working? Keep the mqtt disabled and test with carscanner see if you can see values other than the 12V battery voltage. The 12V battery reading is not done through CAN.
> 
> First we need to figure out what is causing the climate control to act up before we set it up.

climate control is back to normal now. climate working with these settings:
![image](https://github.com/user-attachments/assets/762434ab-94c3-482a-ba7e-3eec9a55377c)
![image](https://github.com/user-attachments/assets/2d3b5581-2a20-4a6d-8b7a-40585db1bca8)
![image](https://github.com/user-attachments/assets/77e581b4-0ce7-4c3a-897a-e405591cd15b)

**Comment by meatpiHQ** [comment]
@tung256 OK That's great. Now update to beta version https://github.com/meatpiHQ/wican-fw/releases/tag/v3.11Beta

Then in the automate tab add these values and click store. Reference:  https://github.com/meatpiHQ/wican-fw/discussions/157#discussioncomment-10168102

initialisation: ATSH7E4;ATST96;
expression: B10/2
Pid: 2201019

![image](https://github.com/user-attachments/assets/75c68355-f24d-454d-8b23-38d34059a22b)

**Comment by tung256** [comment]
fw updated as you wanted
![image](https://github.com/user-attachments/assets/1f96734f-faee-49b9-b6d1-679a5e4a8eb5)
Automate tab done as you wanted. i rebooted WiCAN too
![image](https://github.com/user-attachments/assets/34b2fd41-5bb6-4c06-a188-94d392a88163)
CAN settings as before
![image](https://github.com/user-attachments/assets/86189a75-0436-4582-80b4-b0d34abc7177)
![image](https://github.com/user-attachments/assets/e0793a8a-1652-4435-ae20-f6a516752765)
no SOC in my MQTT as seen here
![image](https://github.com/user-attachments/assets/3a0728c3-b13e-4986-a1aa-7ca1f840e7c3)

**Comment by meatpiHQ** [comment]
@tung256 I forgot to mention you should change the protocol to "autopid" instead of elm327

**Comment by tung256** [comment]
@meatpiHQ im very happy to say it works once i change to autopid!
values came through every 2s:
![image](https://github.com/user-attachments/assets/9bb2e5dd-4962-4524-af46-ec4b57052c88)

now, is there a CSV file containing more Init, PID, and Expression?
i see you shared this file from [this post](https://github.com/meatpiHQ/wican-fw/discussions/157#discussioncomment-10168102):
![image](https://github.com/user-attachments/assets/0747bf5e-17f2-49fd-a9e8-c84c120dd94c)
but it makes absolutely no sense for my Ioniq5 as i dont see PID 2201019  in that csv file

**Comment by meatpiHQ** [comment]
@tung256 seems like the Ioniq 5 has the same PIDs as the Kona. I haven't had a chance to investigate this yet. 

Note that, the PID is 220101 and the 9 at the end indicates it's expecting 9 frames.

**Comment by tung256** [comment]
@meatpiHQ 
in our example of SOC, i see the equation you wrote is B10/2:
![image](https://github.com/user-attachments/assets/41a9a396-7fd2-49ba-b9da-ce75d9e62466)
BUT in the CSV file, i see it is just E/2   so this is very confusing.

_can we please do another example?_
![image](https://github.com/user-attachments/assets/8755511e-4285-436c-bbea-a3eeb54ce50f)
what should i put in for init, PID and expression?
your time and help is greatly appreciated!

**Comment by tung256** [comment]
@meatpiHQ   just want to let you know SOC is now available in my Home Assistant once i add this code into my configuration.yml file
![image](https://github.com/user-attachments/assets/1d2f394e-6f74-4c4e-bc6a-3ee559d86d31)

it parses the MQTT from SoC_topic to give me this:
![image](https://github.com/user-attachments/assets/2bae50ee-b37c-41e3-b2dc-7289e3076a88)
your product is amazing!

now just waiting on your help to get the voltage reading from the 12v battery, which i believe is labeled as "Aux Batt Volts" from your csv file

**Comment by meatpiHQ** [comment]
@tung256 glad to hear it's working for you.

Here is an example of how to interrupt the data based on the CSV file.

Below is the raw data from all the frames read by wican, the letters on top of the bytes, is how the CSV file represents the bytes, 

'a' is B5
'e' is B10 
'ad' is  B38

If you want read the battery voltage you should use the expression: B38*0.1

In the future you don't have to worry about doing this, the new update will include your car model and all the supported parameters in the PID response.

```
               a   b  c
10 3E 62 01 01 EF FB E7
   d  e  f  g  h   i  j
21 EF 84 20 40 01 72 00
   k  l  m   n  o  p  q
22 FF D0 1D 1A 19 17 18
    r  s  t  u  v  w  x  
23 19 18 18 18 00 3F C2
   y  z  aa ab ac ad af 
24 16 C1 0E 00 00 90 00
   ag 
25 00 F1 D5 00 00 ED DF
26 00 00 B4 D5 00 00 AD
27 12 00 8D 9C 5F 00 02
28 E7 00 00 00 00 07 07
```

**Comment by tung256** [comment]
i still dont know how to read raw. will try again and again since im not smart.
but at least i got these 2 working and very happy thanks to you!
![image](https://github.com/user-attachments/assets/c58355b2-a14e-4f08-825b-7fb1b34a6321)

![image](https://github.com/user-attachments/assets/43040050-aaa3-4e80-94ff-6aefa65c19f9)

yes, i think future update to just select make, model, and year would alleviate a lot of confusion for amateurs like myself. thank you for all your help

**Comment by erpalma** [comment]
I'm trying to replicate this on a Ioniq 6, which has the very same PIDs. Indeed I can confirm that 220101 works by looking at the logs in car scanner, and trying using the elm327 protocol manually. The car responds and B10/2 seems correct if I manually parse the response frames. My problem is that the Automate feature does not seems to work correctly: i can see that WiCAN is sending the request since I can see the response coming back at the "rx" topic. However I can't see the parsed JSON topic (i.e. "SoC_topic in this case). Everything is configured as per this issue, I've triple-checked everything. How can I debug this issue?

**Comment by meatpiHQ** [comment]
@tung256 @erpalma this might be of interest to you https://github.com/meatpiHQ/wican-fw/discussions/157#discussioncomment-10298587

I will add more parameters for the Ioniq later.

**Comment by tung256** [comment]
im sorry it does not make any sense to me on how to decode.



  in your example, i see "a" is directly over EF.  how does "a" becomes B5?
 i see "ad" is over 90,  but it becomes B38?

is there a video guide that can explain? or what keywords should i search on YouTube? i searched for CAN bus but not of them explained how to read MQTT raw files...


On Thursday, August 8, 2024 at 07:13:21 AM EDT, MeatPi Electronics ***@***.***> wrote:  
 
 


@tung256 glad to hear it's working for you.

Here is an example of how to interrupt the data based on the CSV file.

Below is the raw data from all the frames read by wican, the letters on top of the bytes, is how the CSV file represents the bytes,

'a' is B5
'e' is B10
'ad' is B38

If you want read the battery voltage you should use the expression: B38*0.1

In the future you don't have to worry about doing this, the new update will include your car model and all the supported parameters in the PID response.
               a   b  c
10 3E 62 01 01 EF FB E7
   d  e  f  g  h   i  j
21 EF 84 20 40 01 72 00
   k  l  m   n  o  p  q
22 FF D0 1D 1A 19 17 18
    r  s  t  u  v  w  x  
23 19 18 18 18 00 3F C2
   y  z  aa ab ac ad af 
24 16 C1 0E 00 00 90 00
   ag 
25 00 F1 D5 00 00 ED DF
26 00 00 B4 D5 00 00 AD
27 12 00 8D 9C 5F 00 02
28 E7 00 00 00 00 07 07
