### ISSUE TITLE
Generic Profile: Odometer Issue

### ISSUE THREAD

**Issue by cloudbr34k84** [meatpiHQ/wican-fw#208]
[log (1).txt](https://github.com/user-attachments/files/17051263/log.1.txt)
attached is my car scanner log file. Im unable to get a reading on my odomter. In car Scanner, i was able to see Odometer Engine that shows my odometer number.

**Comment by cloudbr34k84** [comment]
@meatpiHQ any chance of having a look at this?

**Comment by meatpiHQ** [comment]
@cloudbr34k84 what was your odometer reading when you exported this log?

**Comment by cloudbr34k84** [comment]
> @cloudbr34k84 what was your odometer reading when you exported this log?

Sorry no idea

**Comment by cloudbr34k84** [comment]
@meatpiHQ 
[engine_odometer.txt](https://github.com/user-attachments/files/17157868/engine_odometer.txt)
![Screenshot_20240927-114302](https://github.com/user-attachments/assets/9404169d-c994-40c7-b650-cdcd5096a562)

**Comment by meatpiHQ** [comment]
@cloudbr34k84 

Please try adding this to the custom PID first. And use mqtt explore to check

<img width="770" alt="image" src="https://github.com/user-attachments/assets/7d46a9a5-9ef4-4a09-bd13-809de728e50f">

**Comment by cloudbr34k84** [comment]
closing this off Thank you

**Comment by cloudbr34k84** [comment]
@meatpiHQ  how do we go about setting up a profile for Colorado??
