### ISSUE TITLE
Links to firmware update broken

### ISSUE THREAD

**Issue by EnochPrime** [meatpiHQ/wican-fw#210]
The links in `README.md` to the firmware update process are broken. It looks like the docs were moved in commit https://github.com/meatpiHQ/wican-fw/commit/10ce69f96c9c8df51c2bd979b502eae1e289cf10

**Comment by meatpiHQ** [comment]
@EnochPrime Yes move to the [Official Docs](https://meatpihq.github.io/wican-fw/)

I'll fix the readme.
