### ISSUE TITLE
WiCAN-OBD2 stops working when automatic bit rate is selected

### ISSUE THREAD

**Issue by MarcosAPMT** [meatpiHQ/wican-fw#273]
Hi. I've been testing a WiCAN-OBD2 which completely stops working after selecting auto bitrate in version 3.48. The only way to fix it is to re-flash the firmware with the recovery tool. The behaviour is the same every time I enable the setting.

**Comment by meatpiHQ** [comment]
@MarcosAPMT I'm planning to remove the  auto bitrate in the next revision.

**Comment by MarcosAPMT** [comment]
This is acceptable. Thanks
