### ISSUE TITLE
Feature request: Emulation mode

### ISSUE THREAD

**Issue by humbertogontijo** [meatpiHQ/wican-fw#32]
Would be super nice to be able to record some obd traffic, leave the car, and use the usb port of the WiCAN-OBD2 to power it on and run that record emulated for debugging purpose.

**Comment by meatpiHQ** [comment]
@humbertogontijo ok but why not just use BUSMaster or savvyCAN to record the messages?

**Comment by humbertogontijo** [comment]
Another question I have. I'm using v1.69, and when I try to change ble from disabled to enabled the combo box gets greyed out. Any idea what it can be?

**Comment by meatpiHQ** [comment]
Disable MQTT and wifi station mode. This will enable BLE option.
