### ISSUE TITLE
SLCAN messages/MQTT dependency?

### ISSUE THREAD

**Issue by wrightbuilt** [meatpiHQ/wican-fw#40]
I am trying to access raw can bus messages over TCP. It seems, however that it only works when MQTT is active. When MQTT is disabled, I am not seeing the messages on TCP 3333. 

Here are my setting:

<img width="369" alt="Screenshot 2023-04-24 at 11 25 39 AM" src="https://user-images.githubusercontent.com/15802973/234058099-e3568e0c-649d-4150-b726-16cc32e13645.png">

I created this simple python script for the test: 

```
import socket

HOST = '192.168.50.103'  # Replace with the server's IP address
PORT = 3333  # Use the same port number as the server

def receive_can_messages():
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect((HOST, PORT))
        while True:
            data = s.recv(1024)
            if not data:
                break
            print(f'Received CAN message: {data.decode()}')

if __name__ == '__main__':
    receive_can_messages()
```

 As long as MQTT is enabled, I will get messages. However, if MQTT is disabled, I get no messages. The should not be a dependency between TCP and MQTT right?

**Comment by meatpiHQ** [comment]
@rv10guy If you want to use SLCAN you should use the python library. SLCAN needs so send commands to the bus the initialize it. You can replace CAN_DEV with IP address if you're using WiFi.

https://github.com/meatpiHQ/programming_examples/tree/master/CAN/python
https://github.com/meatpiHQ/programming_examples/blob/master/CAN/python/vscansend.py

**Comment by rv10guy** [comment]
@meatpiHQ Awesome. Fixed several issues, I had. I never thought of looking in a different repository for examples. That is good stuff! Thanks
