### ISSUE TITLE
Discord sever invite link broken?

### ISSUE THREAD

**Issue by EnochPrime** [meatpiHQ/wican-fw#72]
I tried to follow the discord link in the README and it did not work.

![image](https://github.com/meatpiHQ/wican-fw/assets/1175190/cef5f767-5dda-4e9e-b8f1-51611d635c17)

**Comment by meatpiHQ** [comment]
@EnochPrime I've updated the link, please try again

**Comment by EnochPrime** [comment]
The link works now. Thanks!
Fixed via commit ec709c2
