### ISSUE TITLE
Custom MQTT topics

### ISSUE THREAD

**Issue by MarcosAPMT** [meatpiHQ/wican-fw#88]
Hi, I have been testing the WiCAN-OBD2 and I have seen that it is not possible to manually configure the MQTT topic to which the device publishes. My idea of use is for fleets of vehicles managed by third parties and not being able to configure the topics makes this implementation very difficult for several reasons. Would it be possible to add this feature? Thank you.

**Comment by MarcosAPMT** [comment]
Yes, I am aware of this limitation. In principle this is not a major constraint for us, at least for some tests. The equipment is located within a closed, secured network. 

As I said, being able to configure the topics is very important for us.

I appreciate your help and quick response. Best regards.

**Comment by meatpiHQ** [comment]
Now there's only one receive and transmit topics, do you want to make those configurable?

**Comment by MarcosAPMT** [comment]
Yes, and also the status topic. Right now, both CAN and status topics are located in wican/xxxxxxxxxxxx. My request is to at least be able to change the xxxxxxxxxxxxxxx part to an arbitrary value. This would make it easier for us to know from which vehicle we are receiving data.

**Comment by meatpiHQ** [comment]
xxxxxxxxxxxx is the device ID and it unique, not a random value.

**Comment by MarcosAPMT** [comment]
Oh, I know this. But as I mentioned, for our use case, these devices are operated by third-party workers. Having them take note of the ID of the device installed in each vehicle and send it to us is rather unreliable. It is important for us to know exactly which vehicle in the fleet a device is installed in, and as I said, if the topics could be configured, this would be more than enough for us.

**Comment by meatpiHQ** [comment]
@MarcosAPMT I'll add this feature soon.

**Comment by meatpiHQ** [comment]
@MarcosAPMT Please try this firmware, all 3 topics are now configurable. 

<img width="266" alt="image" src="https://github.com/meatpiHQ/wican-fw/assets/94690098/8caec301-bd90-4184-ad71-3c3d331ef172">


[wican-fw_v297_hv300.zip](https://github.com/meatpiHQ/wican-fw/files/14448508/wican-fw_v297_hv300.zip)

**Comment by MarcosAPMT** [comment]
@meatpiHQ Thanks a lot. Will try this tomorrow and revert.

**Comment by MarcosAPMT** [comment]
@meatpiHQ Hello. I've been able to test and it's working well. Looks like the CAN message filtering is different is this version, so the old config didn't work for me.

**Comment by meatpiHQ** [comment]
@MarcosAPMT set the index in the filter to 2. You'll get the same behaviour as before.

**Comment by MarcosAPMT** [comment]
This seems to be working well. I think the issue can be closed once this is implemented in a final release. Thanks a lot!
